name: Testing GitHub Actions workflow
on: workflow_dispatch
env:
  TEST: Hello
jobs:
  first_test:
    runs-on: ubuntu-latest
    env:
      TEST: Hi
    steps:
      - run: echo ${{ env.TEST }}
  second_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.TEST }}
