name: Testing GitHub Actions workflow
on: workflow_dispatch
env:
  TEST: Hello
  TEST2: ${{ env.TEST }}
jobs:
  first_test:
    runs-on: ubuntu-latest
    env:
      TEST: Hi
    steps:
      - run: echo ${{ env.TEST }}
  second_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TEST
          echo $TEST2
          echo $TEST3
          echo $TEST4
