name: Testing GitHub Actions workflow
on: workflow_dispatch
env:
  TEST: Hello
jobs:
  first_test:
    runs-on: ubuntu-latest
    env:
      TEST: Hi
    steps:
      - run: |
          echo ${{ env.TEST }}
          echo $TEST
          echo "TEST2=test2" >> $GITHUB_ENV
          export TEST3=test3
      - run: |
          echo ${{ env.TEST2 }}
          echo $TEST2
          echo $TEST3
  second_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TEST
          echo $TEST2
          echo ${{ env.TEST2 }}
