name: Testing GitHub Actions workflow
on: workflow_dispatch
jobs:
  first_test:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: pwd
      - run: whoami
      - run: cd ..
      - run: ls -al
