name: Test workflow 2
on:
  push:
    branches:
      - "dev"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Debug all GitHub context
      run: echo "$GITHUB_CONTEXT" | jq .
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Print from dev branch
      run: echo "Hi I'm dev branch"
